app:
  name: ginApi
  port: :8088
  mode: release

mysql:
  conn: root:123456@tcp(127.0.0.1:3306)/tableName?charset=utf8mb4&parseTime=true&loc=Local

redis:
  host:127.0.0.1
  port: 6379
  password: 123456
  db: 1
